"""add staff_id to users

Revision ID: 1234fae65c1c
Revises: 3b4cf25d3e3d
Create Date: 2026-05-13 10:39:07.595039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1234fae65c1c'
down_revision: Union[str, Sequence[str], None] = '3b4cf25d3e3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('doctor_id', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_appointments_doctor_id'), 'appointments', ['doctor_id'], unique=False)
    op.add_column('users', sa.Column('staff_id', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_users_staff_id'), 'users', ['staff_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_staff_id'), table_name='users')
    op.drop_column('users', 'staff_id')
    op.drop_index(op.f('ix_appointments_doctor_id'), table_name='appointments')
    op.drop_column('appointments', 'doctor_id')
    # ### end Alembic commands ###
