"""add_expected_payment_date_to_invoices

Revision ID: 12ba5adb3bd2
Revises: fdb81bfbce02
Create Date: 2026-05-22 10:01:05.240850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12ba5adb3bd2'
down_revision: Union[str, Sequence[str], None] = 'fdb81bfbce02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('expected_payment_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'expected_payment_date')
    # ### end Alembic commands ###
