"""add_price_to_medicines

Revision ID: 1419d554295c
Revises: 665de377e23b
Create Date: 2026-05-08 12:37:23.376183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1419d554295c'
down_revision: Union[str, Sequence[str], None] = '665de377e23b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column as nullable first so existing rows are not rejected
    op.add_column('medicines', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True))
    # Backfill existing rows with 0.00
    op.execute("UPDATE medicines SET price = 0.00 WHERE price IS NULL")
    # Now enforce NOT NULL
    op.alter_column('medicines', 'price', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medicines', 'price')
    # ### end Alembic commands ###
