"""add_cash_receipts_table

Revision ID: 15dbb66b87a5
Revises: f1d301c7134a
Create Date: 2026-05-27 11:57:11.955397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15dbb66b87a5'
down_revision: Union[str, Sequence[str], None] = 'f1d301c7134a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('invoice_code', sa.String(length=20), nullable=False),
    sa.Column('patient_name', sa.String(length=120), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_receipts_id'), 'cash_receipts', ['id'], unique=False)
    op.create_index(op.f('ix_cash_receipts_invoice_code'), 'cash_receipts', ['invoice_code'], unique=False)
    op.create_index(op.f('ix_cash_receipts_owner_user_id'), 'cash_receipts', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_cash_receipts_patient_name'), 'cash_receipts', ['patient_name'], unique=False)
    
    # Retrospectively populate cash receipts for existing invoice payments
    op.execute(
        "INSERT INTO cash_receipts (owner_user_id, invoice_code, patient_name, amount_paid, payment_date, created_at) "
        "SELECT owner_user_id, invoice_code, patient_name, amount_paid, invoice_date, CURRENT_TIMESTAMP "
        "FROM invoices WHERE amount_paid > 0"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cash_receipts_patient_name'), table_name='cash_receipts')
    op.drop_index(op.f('ix_cash_receipts_owner_user_id'), table_name='cash_receipts')
    op.drop_index(op.f('ix_cash_receipts_invoice_code'), table_name='cash_receipts')
    op.drop_index(op.f('ix_cash_receipts_id'), table_name='cash_receipts')
    op.drop_table('cash_receipts')
    # ### end Alembic commands ###
