"""add_ambulances_table

Revision ID: 1c69af229113
Revises: 12ba5adb3bd2
Create Date: 2026-05-22 11:15:50.512250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c69af229113'
down_revision: Union[str, Sequence[str], None] = '12ba5adb3bd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ambulances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('ambulance_code', sa.String(length=20), nullable=False),
    sa.Column('vehicle_number', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('driver_name', sa.String(length=120), nullable=True),
    sa.Column('driver_contact', sa.String(length=20), nullable=True),
    sa.Column('paramedic_name', sa.String(length=120), nullable=True),
    sa.Column('equipment_checklist', sa.String(length=255), nullable=True),
    sa.Column('current_trip_patient', sa.String(length=120), nullable=True),
    sa.Column('current_trip_destination', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ambulances_ambulance_code'), 'ambulances', ['ambulance_code'], unique=True)
    op.create_index(op.f('ix_ambulances_id'), 'ambulances', ['id'], unique=False)
    op.create_index(op.f('ix_ambulances_owner_user_id'), 'ambulances', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_ambulances_status'), 'ambulances', ['status'], unique=False)
    op.create_index(op.f('ix_ambulances_vehicle_number'), 'ambulances', ['vehicle_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ambulances_vehicle_number'), table_name='ambulances')
    op.drop_index(op.f('ix_ambulances_status'), table_name='ambulances')
    op.drop_index(op.f('ix_ambulances_owner_user_id'), table_name='ambulances')
    op.drop_index(op.f('ix_ambulances_id'), table_name='ambulances')
    op.drop_index(op.f('ix_ambulances_ambulance_code'), table_name='ambulances')
    op.drop_table('ambulances')
    # ### end Alembic commands ###
