"""Add emergency contact field to appointments

Revision ID: 3b4cf25d3e3d
Revises: e3bd86473f46
Create Date: 2026-05-11 16:33:10.652386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b4cf25d3e3d'
down_revision: Union[str, Sequence[str], None] = 'e3bd86473f46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('emergency_contact', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'emergency_contact')
    # ### end Alembic commands ###
