"""sync_appointments_schema

Revision ID: 665de377e23b
Revises: 87efa0a33606
Create Date: 2026-05-06 15:56:17.132235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '665de377e23b'
down_revision: Union[str, Sequence[str], None] = '87efa0a33606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('scheduled_later_reason', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_appointments_doctor_name'), table_name='appointments')
    op.alter_column('patients', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_index(op.f('ix_appointments_doctor_name'), 'appointments', ['doctor_name'], unique=False)
    op.drop_column('appointments', 'scheduled_later_reason')
    # ### end Alembic commands ###
