"""add symptoms to appointments

Revision ID: 6c7f46873cc5
Revises: f55f59871e97
Create Date: 2026-05-19 19:18:40.933688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c7f46873cc5'
down_revision: Union[str, Sequence[str], None] = 'f55f59871e97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('symptoms', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'symptoms')
    # ### end Alembic commands ###
