"""Add patient_name and allotment_reason to beds

Revision ID: 6f768c0b83fa
Revises: f4775093cdb6
Create Date: 2026-05-18 10:57:52.910624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f768c0b83fa'
down_revision: Union[str, Sequence[str], None] = 'f4775093cdb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beds', sa.Column('patient_name', sa.String(length=120), nullable=True))
    op.add_column('beds', sa.Column('allotment_reason', sa.String(length=255), nullable=True))
    op.drop_column('users', 'permissions')
    op.drop_column('users', 'full_crud_access')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_crud_access', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('permissions', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_column('beds', 'allotment_reason')
    op.drop_column('beds', 'patient_name')
    # ### end Alembic commands ###
