"""add_gst_columns_to_invoices

Revision ID: 72d41e0d7b76
Revises: 794392fc09a6
Create Date: 2026-05-22 09:35:23.866897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72d41e0d7b76'
down_revision: Union[str, Sequence[str], None] = '794392fc09a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('cgst', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('sgst', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('igst', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'igst')
    op.drop_column('invoices', 'sgst')
    op.drop_column('invoices', 'cgst')
    # ### end Alembic commands ###
