"""add_medicine_transactions_table

Revision ID: 794392fc09a6
Revises: bafc908c9a74
Create Date: 2026-05-20 13:52:29.824158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '794392fc09a6'
down_revision: Union[str, Sequence[str], None] = 'bafc908c9a74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicine_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('medicine_name', sa.String(length=120), nullable=False),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('invoice_code', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicine_transactions_id'), 'medicine_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_medicine_transactions_medicine_id'), 'medicine_transactions', ['medicine_id'], unique=False)
    op.create_index(op.f('ix_medicine_transactions_owner_user_id'), 'medicine_transactions', ['owner_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medicine_transactions_owner_user_id'), table_name='medicine_transactions')
    op.drop_index(op.f('ix_medicine_transactions_medicine_id'), table_name='medicine_transactions')
    op.drop_index(op.f('ix_medicine_transactions_id'), table_name='medicine_transactions')
    op.drop_table('medicine_transactions')
    # ### end Alembic commands ###
