"""add_telegram_chat_id_to_appointments

Revision ID: 7af55acb816a
Revises: 69807f691ba3
Create Date: 2026-04-17 15:19:06.194990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7af55acb816a'
down_revision: Union[str, Sequence[str], None] = '69807f691ba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('telegram_chat_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'telegram_chat_id')
    # ### end Alembic commands ###
