"""add phone_number time_slot department to appointments

Revision ID: 87efa0a33606
Revises: 7af55acb816a
Create Date: 2026-04-28 09:54:07.168978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87efa0a33606'
down_revision: Union[str, Sequence[str], None] = '7af55acb816a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('phone_number', sa.String(length=30), nullable=True))
    op.add_column('appointments', sa.Column('time_slot', sa.String(length=30), nullable=True))
    op.add_column('appointments', sa.Column('department', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'department')
    op.drop_column('appointments', 'time_slot')
    op.drop_column('appointments', 'phone_number')
    # ### end Alembic commands ###
