"""add_amount_paid_to_invoices

Revision ID: b50a7ea39e84
Revises: 6f768c0b83fa
Create Date: 2026-05-18 11:53:45.405199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b50a7ea39e84'
down_revision: Union[str, Sequence[str], None] = '6f768c0b83fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'amount_paid')
    # ### end Alembic commands ###
