"""add_sample_id_to_blood_activities

Revision ID: bafc908c9a74
Revises: 6c7f46873cc5
Create Date: 2026-05-20 13:42:35.735333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bafc908c9a74'
down_revision: Union[str, Sequence[str], None] = '6c7f46873cc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blood_activities', sa.Column('sample_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blood_activities', 'sample_id')
    # ### end Alembic commands ###
