"""Add emergency contact fields to patients

Revision ID: e3bd86473f46
Revises: 93db3e80ee0b
Create Date: 2026-05-11 16:22:41.216217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3bd86473f46'
down_revision: Union[str, Sequence[str], None] = '93db3e80ee0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('emergency_contact_1', sa.String(length=20), nullable=True))
    op.add_column('patients', sa.Column('emergency_contact_2', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'emergency_contact_2')
    op.drop_column('patients', 'emergency_contact_1')
    # ### end Alembic commands ###
