"""add_patient_id

Revision ID: e52021b2f6d9
Revises: 90f064a91b0d
Create Date: 2026-04-14 13:35:49.717090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e52021b2f6d9'
down_revision: Union[str, Sequence[str], None] = '90f064a91b0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('patient_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'appointments', 'patients', ['patient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'patient_id')
    # ### end Alembic commands ###
