"""add full_crud_access and permissions to users

Revision ID: f4775093cdb6
Revises: 1234fae65c1c
Create Date: 2026-05-14 10:55:03.256752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4775093cdb6'
down_revision: Union[str, Sequence[str], None] = '1234fae65c1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('appointments_booking_id_key'), 'appointments', type_='unique')
    op.create_index(op.f('ix_appointments_booking_id'), 'appointments', ['booking_id'], unique=True)
    op.add_column('users', sa.Column('full_crud_access', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('permissions', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'permissions')
    op.drop_column('users', 'full_crud_access')
    op.drop_index(op.f('ix_appointments_booking_id'), table_name='appointments')
    op.create_unique_constraint(op.f('appointments_booking_id_key'), 'appointments', ['booking_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
