"""add_missing_invoice_columns

Revision ID: f55f59871e97
Revises: b50a7ea39e84
Create Date: 2026-05-19 11:19:02.587596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f55f59871e97'
down_revision: Union[str, Sequence[str], None] = 'b50a7ea39e84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('due_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('invoices', sa.Column('tax_total', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('invoices', sa.Column('discount_total', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('invoices', sa.Column('payment_status', sa.String(length=30), nullable=False))
    op.add_column('invoices', sa.Column('billing_type', sa.String(length=10), nullable=False))
    op.add_column('invoices', sa.Column('admission_id', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('ward_name', sa.String(length=120), nullable=True))
    op.add_column('invoices', sa.Column('stay_duration_days', sa.Integer(), nullable=True))
    op.add_column('invoices', sa.Column('room_charge_per_day', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('room_charges', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('insurance_provider', sa.String(length=120), nullable=True))
    op.add_column('invoices', sa.Column('policy_number', sa.String(length=80), nullable=True))
    op.add_column('invoices', sa.Column('covered_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('remaining_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.create_index(op.f('ix_invoices_payment_status'), 'invoices', ['payment_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_payment_status'), table_name='invoices')
    op.drop_column('invoices', 'remaining_amount')
    op.drop_column('invoices', 'covered_amount')
    op.drop_column('invoices', 'policy_number')
    op.drop_column('invoices', 'insurance_provider')
    op.drop_column('invoices', 'room_charges')
    op.drop_column('invoices', 'room_charge_per_day')
    op.drop_column('invoices', 'stay_duration_days')
    op.drop_column('invoices', 'ward_name')
    op.drop_column('invoices', 'admission_id')
    op.drop_column('invoices', 'billing_type')
    op.drop_column('invoices', 'payment_status')
    op.drop_column('invoices', 'discount_total')
    op.drop_column('invoices', 'tax_total')
    op.drop_column('invoices', 'due_amount')
    # ### end Alembic commands ###
