"""add payment_notes to invoices

Revision ID: fdb81bfbce02
Revises: 72d41e0d7b76
Create Date: 2026-05-22 09:47:02.305727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdb81bfbce02'
down_revision: Union[str, Sequence[str], None] = '72d41e0d7b76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('payment_notes', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'payment_notes')
    # ### end Alembic commands ###
