// Auto-generated by `npx boneyard-js build` — do not edit manually
import { registerBones } from 'boneyard-js/react'

import _dashboard_stats from './dashboard-stats.bones.json'
import _dashboard_queue from './dashboard-queue.bones.json'
import _patients_table from './patients-table.bones.json'
import _appointments_table from './appointments-table.bones.json'
import _billing_table from './billing-table.bones.json'
import _emr_table from './emr-table.bones.json'
import _pharmacy_table from './pharmacy-table.bones.json'
import _lab_table from './lab-table.bones.json'
import _beds_grid from './beds-grid.bones.json'
import _staff_table from './staff-table.bones.json'
import _inventory_table from './inventory-table.bones.json'
import _bloodbank_inventory from './bloodbank-inventory.bones.json'
import _bloodbank_activities from './bloodbank-activities.bones.json'
import _reports_grid from './reports-grid.bones.json'
import _reports_advisory from './reports-advisory.bones.json'

registerBones({
  'dashboard-stats': _dashboard_stats,
  'dashboard-queue': _dashboard_queue,
  'patients-table': _patients_table,
  'appointments-table': _appointments_table,
  'billing-table': _billing_table,
  'emr-table': _emr_table,
  'pharmacy-table': _pharmacy_table,
  'lab-table': _lab_table,
  'beds-grid': _beds_grid,
  'staff-table': _staff_table,
  'inventory-table': _inventory_table,
  'bloodbank-inventory': _bloodbank_inventory,
  'bloodbank-activities': _bloodbank_activities,
  'reports-grid': _reports_grid,
  'reports-advisory': _reports_advisory,
})
